---
title: "DATA 607 Project 3"
author: Harris Dupre, Scott Reed, William Outcault, Diane DeOcampo, Stephen Haslett, Samuel Kigamba, Emmanuel Hayble-Gomes
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(DBI)
library(RMariaDB)
library(data.table)
library(dplyr)
library(dbplyr)
library(tidyverse)
library(kableExtra)
library(knitr)
library(stringr)
```

##Connect to the MYSQL database containing the data science meetup and keywords data.##
```{r, eval=TRUE}
con <- dbConnect(MariaDB(),host="data607.mysql.database.azure.com", dbname="data607",username="data607@data607", client.flag = CLIENT_COMPRESS, password="!WORK,open,DOWN!")
```


##Read the "keyword_raw" database table and output the data as Bootstrap table.##
```{r, eval=TRUE}
keywords <- dbReadTable(con, "keyword_raw")
keywords %>% kable() %>% kable_styling(bootstrap_options = c('striped', 'bordered')) %>% row_spec(row = 0, color = "black")
```


##Read the "events" database table and output the data as a Bootstrap table.##
```{r, eval=TRUE}
meetup_events <- dbReadTable(con, "events")
meetup_events %>% kable() %>% kable_styling(bootstrap_options = c('striped', 'bordered'), full_width = TRUE) %>%
  row_spec(row = 0, color = "black", font_size = 15) #%>%
  #scroll_box(height = '300px')
```


##Count the occurence of each keyword in the "description" column of the events database table.##
```{r, eval=TRUE}
keyword_scan<-sapply(keywords$Keyword, function(x){str_count(meetup_events$description, x)})
#keyword_scan<-sapply(keywords$Keyword, function(x){str_count(as.data.frame('This'), x)})
count_results<-colSums(keyword_scan)
count_results
```


##Close the database connection.##
```{r, eval=TRUE}
dbDisconnect(con)
```